-- 1. Procedimiento para insertar miembros

DELIMITER ;

CALL INSERTAR_MIEMBROS("ADRIAN", "ORTIZ", "DXNIEL732@GMAIL.COM", "3173109599", "2023-10-15", 1);

SELECT * FROM MIEMBROS;

-- 2. CREAR UN PROCEDIMIENTO PARA ACTUALIZAR EL PRECIO DE UN PRODUCTO

DELIMITER //

CREATE PROCEDURE ACTUALIZAR_PRECIO(IN ID_PRODUCTO INT, IN NUEVO_PRECIO DECIMAL(10,2))
BEGIN
	UPDATE
		PRODUCTOS_DEPORTIVOS
	SET
		PRODUCTOS_DEPORTIVOS.PRECIO = NUEVO_PRECIO
	WHERE
		PRODUCTOS_DEPORTIVOS.ID_PRODUCTO_DEPORTIVO = ID_PRODUCTO;

END //

DELIMITER ;

SELECT * FROM PRODUCTOS_DEPORTIVOS WHERE PRODUCTOS_DEPORTIVOS.ID_PRODUCTO_DEPORTIVO = 2;

CALL ACTUALIZAR_PRECIO(2, 50.26);

-- 3. CREAR UN PROCEDIMIENTO PARA ELIMINAR UN MIEMBRO

DELIMITER //
CREATE PROCEDURE ELIMINAR_MIEMBRO(IN ID_MIEMBRO INT)
BEGIN
	DELETE FROM
		MIEMBROS
	WHERE
		MIEMBROS.ID_MIEMBRO = ID_MIEMBRO;
END //
DELIMITER ;

SELECT * FROM MIEMBROS;

CALL ELIMINAR_MIEMBRO(11);

-- 4. CREAR UN PROCEDIMIENTO PARA CONSULTAR TODAS LAS CLASES GRUPALES DE UN ENTRENADOR

DELIMITER //

CREATE PROCEDURE TODAS_CLASES_ENTRENADOR(IN ID_ENTRENADOR INT)
BEGIN
	SELECT * FROM CLASES_GRUPALES WHERE CLASES_GRUPALES.ID_ENTRENADOR = ID_ENTRENADOR;
END //

DELIMITER ;

CALL TODAS_CLASES_ENTRENADOR(1);